### ISSUE TITLE
Address language in paper

### ISSUE THREAD

**Issue by AnthonyOfSeattle** [difuture-lmu/dsBinVal#13]
The paper states the following:
>These techniques alleviate many of the administrative, ethical and legal requirements on medical research.

It is unclear how distributed analysis alleviates any of these requirements. I would understand if this statement was about how distributed techniques allow researchers to more easily meet these requirements.

I left this comment out of the copy-editing issue since it is more substantive.

**Comment by schalkdaniel** [comment]
Thanks, this is a good point. I tried to make it more clear by adjusting the text:

- **Original:** "These techniques alleviate many of the administrative, ethical and legal requirements on medical research."
- **Update:** "Since no sensitive information is shared through the use of privacy-preserving and distributed algorithms, their use helps to alleviate administrative, ethical, and legal requirements in medical research as users do not have access to personal data."

**Comment by AnthonyOfSeattle** [comment]
But I believe what I am saying is that the `administrative, ethical, and legal requirements` are still there. They aren't `alleviated`. Do you mean `their use helps to address...` or `their use helps researchers to meet...`?

**Comment by schalkdaniel** [comment]
Now I get it, thanks for pointing it out again. I changed `alleviated` to `meet`, see [4336f13](https://github.com/difuture-lmu/dsBinVal/commit/4336f136887765acbee3e02ca1b06d4c39d8cc7b)

**Comment by AnthonyOfSeattle** [comment]
Thank you for this change. I think it reads well.
